# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Generate essential files for flutter"
  homepage "https://github.com/RafatMeraz/bb"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RafatMeraz/bb/releases/download/0.0.2/bb_Darwin_x86_64.tar.gz"
      sha256 "d151746d17f2800c2adbcab4e68f337575e60f6ab65f74d31151c7669b54a07c"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RafatMeraz/bb/releases/download/0.0.2/bb_Darwin_arm64.tar.gz"
      sha256 "bafc14cf26f10d6ad5168b3a42a15fdd010d7db5a4165851edf9b032d39237e1"

      def install
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/RafatMeraz/bb/releases/download/0.0.2/bb_Linux_x86_64.tar.gz"
      sha256 "b2f5abc8032eb5b3780cd237ce197396a99928c319c65fbeafb3d9aa0f97c29d"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RafatMeraz/bb/releases/download/0.0.2/bb_Linux_arm64.tar.gz"
      sha256 "bb6db9bd787eeeb8e231ed405a43a4bea02a695ec9e9abdd2e4388f1a42fe19b"

      def install
        bin.install "bb"
      end
    end
  end
end
