# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Generate essential files for flutter"
  homepage "https://github.com/RafatMeraz/bb"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RafatMeraz/bb/releases/download/0.0.4/bb_Darwin_x86_64.tar.gz"
      sha256 "d09bfbe05af285ac37f6fb9b1d7efb4d26ceadfab7213c6cde5a72673e6836d4"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RafatMeraz/bb/releases/download/0.0.4/bb_Darwin_arm64.tar.gz"
      sha256 "ecbb09ca48c886e40c8280beae85ccaa80736f0cca2a5349790d1c4fe14f7971"

      def install
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/RafatMeraz/bb/releases/download/0.0.4/bb_Linux_x86_64.tar.gz"
      sha256 "40cc0c53d9a27ae17df79ba51b5292e89fa0d0d80aa818e3f642e928fa85e2ae"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RafatMeraz/bb/releases/download/0.0.4/bb_Linux_arm64.tar.gz"
      sha256 "0df980c7e885da4d923ba6e37efc6d3b9f4ca34176c96cead2b90d2f284421ff"

      def install
        bin.install "bb"
      end
    end
  end
end
