# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Generate essential files for flutter"
  homepage "https://github.com/RafatMeraz/bb"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RafatMeraz/bb/releases/download/0.0.1/bb_Darwin_x86_64.tar.gz"
      sha256 "4351b26ccc1b9e38c03ffb0cfe9132af750b78ae46cdcac0c4a0465ece21903d"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RafatMeraz/bb/releases/download/0.0.1/bb_Darwin_arm64.tar.gz"
      sha256 "f9f6b36237e740ac4d73cc851ebe4f9aca6341554d9c6773e927746db15de276"

      def install
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/RafatMeraz/bb/releases/download/0.0.1/bb_Linux_x86_64.tar.gz"
      sha256 "04add5b3c8447e04dea02bae0dbfcac67040ef3eff6f82f816f8af08bc1ad0aa"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RafatMeraz/bb/releases/download/0.0.1/bb_Linux_arm64.tar.gz"
      sha256 "9175a892d52fbd4ea6e62c491dd3b36ab78c57f5275ae0750e2932fa78a14241"

      def install
        bin.install "bb"
      end
    end
  end
end
